use std::path::Path;

use anyhow::{anyhow, Result};

use crate::{
    activation::{MutationCapability, SelectedActivation},
    activation_platform::ProductionMutationRuntime,
};

fn escape_lisp_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Generate the AutoLISP source that verifies a layout exists, then plots it
/// to `output_pdf` using the layout's existing page setup (non-detailed mode).
///
/// The drawing must have its layout configured with a DWG-To-PDF (file plotter)
/// page setup. If no PDF file appears after the plot, a WARN sentinel is written.
pub fn generate_plot_lsp(layout: &str, output_pdf: &str) -> String {
    let esc_layout = escape_lisp_string(layout);
    let esc_output = escape_lisp_string(output_pdf);

    format!(
        ";; Generated by autocad-mcp — do not edit\n\
         ;; Plots layout \"{esc_layout}\" to \"{esc_output}\"\n\
         (setvar \"BACKGROUNDPLOT\" 0)\n\
         (setvar \"FILEDIA\" 0)\n\
         (setvar \"CMDDIA\" 0)\n\
         \n\
         (defun _mcpplot:run ( / avail)\n\
           (setq avail (layoutlist))\n\
           (if (not (member \"{esc_layout}\" avail))\n\
             (princ (strcat \"\\nRESULT:ERROR:layout-not-found:{esc_layout}\"\n\
                            \" available:\" (vl-princ-to-string avail) \"\\n\"))\n\
             (progn\n\
               ;; Non-detailed mode: uses the layout's existing page setup.\n\
               ;; Prompt order (FILEDIA=0, file plotter):\n\
               ;;   Detailed?=No, Layout=<name>, PageSetup=(accept default),\n\
               ;;   OutputPath=<path>, SaveChanges?=No, Proceed?=Yes\n\
               (command \"_.-PLOT\"\n\
                        \"_No\" \"{esc_layout}\" \"\" \"{esc_output}\" \"_No\" \"_Yes\")\n\
               (if (findfile \"{esc_output}\")\n\
                 (princ \"\\nRESULT:OK:{esc_output}\\n\")\n\
                 (princ \"\\nRESULT:WARN:pdf-not-found-after-plot\\n\")))))\n\
         \n\
         (_mcpplot:run)\n\
         (princ)\n",
    )
}

/// Generate the command script (.scr) that loads and runs the plot LSP.
/// `lsp_path` is the absolute path on disk; backslashes are converted to
/// forward slashes (AutoCAD accepts both on Windows).
pub fn generate_plot_scr(lsp_path: &str) -> String {
    let lsp_forward = lsp_path.replace('\\', "/");
    format!(
        "(setvar \"SECURELOAD\" 0)\n\
         (setvar \"FILEDIA\" 0)(setvar \"CMDDIA\" 0)\n\
         (load \"{lsp_forward}\")\n\
         QUIT\n\
         Y\n"
    )
}

/// Parse accoreconsole stdout for the `RESULT:` sentinel written by the plot
/// script. Returns the confirmed output PDF path on `RESULT:OK:`, `Err` on
/// `RESULT:ERROR:`, `RESULT:WARN:`, or when no sentinel is found.
#[cfg(any(target_os = "windows", test))]
pub(crate) fn parse_plot_output(output: &str) -> Result<String> {
    for line in output.lines() {
        let line = line.trim();
        if let Some(path) = line.strip_prefix("RESULT:OK:") {
            return Ok(path.to_string());
        }
        if let Some(msg) = line.strip_prefix("RESULT:ERROR:") {
            return Err(anyhow!("plot error: {msg}"));
        }
        if let Some(msg) = line.strip_prefix("RESULT:WARN:") {
            return Err(anyhow!("plot warning: {msg}"));
        }
    }
    Err(anyhow!(
        "no RESULT sentinel found in accoreconsole output; \
         the plot script may not have loaded or the prompt sequence did not match. \
         Verify the -PLOT prompt order for this AutoCAD version."
    ))
}

fn validate_plot_request(drawing: &Path, output_pdf: &Path) -> Result<()> {
    let ext = drawing
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();
    if ext != "dwg" {
        return Err(anyhow!(
            "plot_to_pdf only supports DWG input; got '{}'",
            drawing.display()
        ));
    }
    if !output_pdf.is_absolute() {
        return Err(anyhow!(
            "output PDF path must be absolute: '{}'",
            output_pdf.display()
        ));
    }
    Ok(())
}

/// Plot a DWG layout to PDF via accoreconsole.
///
/// Requires accoreconsole (Windows only). The layout must have a file-plotter
/// (DWG To PDF.pc3) page setup already configured in the drawing.
#[cfg(test)]
pub fn plot_to_pdf(drawing: &Path, layout: &str, output_pdf: &Path) -> Result<()> {
    plot_to_pdf_impl(drawing, layout, output_pdf, None)
}

pub fn plot_to_pdf_with_activation(
    drawing: &Path,
    layout: &str,
    output_pdf: &Path,
    runtime: &ProductionMutationRuntime,
) -> Result<()> {
    validate_plot_request(drawing, output_pdf)?;
    let drawing_format = crate::reader::inspect_dwg_version(drawing).map_err(|error| {
        anyhow!("failed to inspect persisted DWG version before plot activation: {error}")
    })?;
    let selected = runtime
        .acquire_for_format(MutationCapability::Plot, &drawing_format)
        .map_err(|error| {
            anyhow!(
                "AutoCAD activation failed before plotting: {error}; drawing={}",
                drawing.display()
            )
        })?;
    plot_to_pdf_impl_after_validation(drawing, layout, output_pdf, Some(&selected))
}

#[cfg(test)]
fn plot_to_pdf_impl(
    drawing: &Path,
    layout: &str,
    output_pdf: &Path,
    selected: Option<&SelectedActivation>,
) -> Result<()> {
    validate_plot_request(drawing, output_pdf)?;
    plot_to_pdf_impl_after_validation(drawing, layout, output_pdf, selected)
}

fn plot_to_pdf_impl_after_validation(
    drawing: &Path,
    layout: &str,
    output_pdf: &Path,
    selected: Option<&SelectedActivation>,
) -> Result<()> {
    #[cfg(not(target_os = "windows"))]
    {
        let _ = (drawing, layout, output_pdf, selected);
        Err(anyhow!(
            "accoreconsole is only available on Windows; \
             cannot plot to PDF on this platform"
        ))
    }

    #[cfg(target_os = "windows")]
    {
        use crate::engine;

        let staging = engine::create_staging_dir()?;
        let staging_path = staging.path();

        let output_str = output_pdf
            .to_str()
            .ok_or_else(|| anyhow!("output PDF path is not valid UTF-8"))?;
        let lsp_content = generate_plot_lsp(layout, output_str);
        let lsp_path = staging_path.join("plot.lsp");
        std::fs::write(&lsp_path, lsp_content)?;

        let lsp_path_str = lsp_path
            .to_str()
            .ok_or_else(|| anyhow!("staging path is not valid UTF-8"))?;
        let scr_content = generate_plot_scr(lsp_path_str);
        let scr_path = staging_path.join("plot.scr");
        std::fs::write(&scr_path, scr_content)?;

        let output = match selected {
            Some(selected) => engine::run_accoreconsole_with_selected_activation(
                selected,
                drawing,
                &scr_path,
                staging_path,
                &[],
            ),
            None => {
                let exe = engine::find_accoreconsole()?;
                engine::run_accoreconsole(&exe, drawing, &scr_path, staging_path)
            }
        }?;
        parse_plot_output(&output).map(|_confirmed_path| ())
        // `staging` drops here, cleaning up the temp dir
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lsp_contains_layout_name() {
        let s = generate_plot_lsp("Layout1", "/tmp/out.pdf");
        assert!(s.contains("Layout1"), "layout name missing:\n{s}");
    }

    #[test]
    fn lsp_contains_output_path() {
        let s = generate_plot_lsp("Layout1", "/tmp/out.pdf");
        assert!(s.contains("/tmp/out.pdf"), "output path missing:\n{s}");
    }

    #[test]
    fn lsp_escapes_double_quotes_in_layout() {
        let s = generate_plot_lsp(r#"My "Special" Layout"#, "/tmp/out.pdf");
        assert!(
            s.contains(r#"My \"Special\" Layout"#),
            "quotes not escaped:\n{s}"
        );
    }

    #[test]
    fn lsp_escapes_backslash_in_output_path() {
        let s = generate_plot_lsp("Layout1", r"C:\Users\username\output.pdf");
        assert!(
            s.contains(r"C:\\Users\\username\\output.pdf"),
            "backslash not escaped:\n{s}"
        );
    }

    #[test]
    fn lsp_contains_result_sentinels() {
        let s = generate_plot_lsp("Layout1", "/tmp/out.pdf");
        assert!(s.contains("RESULT:OK:"), "RESULT:OK: missing:\n{s}");
        assert!(
            s.contains("RESULT:ERROR:layout-not-found:"),
            "RESULT:ERROR: missing:\n{s}"
        );
        assert!(
            s.contains("RESULT:WARN:pdf-not-found-after-plot"),
            "RESULT:WARN: missing:\n{s}"
        );
    }

    #[test]
    fn lsp_uses_layoutlist_to_verify() {
        let s = generate_plot_lsp("Layout1", "/tmp/out.pdf");
        assert!(s.contains("layoutlist"), "layoutlist check missing:\n{s}");
    }

    #[test]
    fn scr_starts_with_secureload_zero() {
        let s = generate_plot_scr("/tmp/plot.lsp");
        let first_line = s.lines().next().unwrap();
        assert_eq!(
            first_line, r#"(setvar "SECURELOAD" 0)"#,
            "SECURELOAD must be first:\n{s}"
        );
    }

    #[test]
    fn scr_contains_load_with_forward_slashes() {
        let s = generate_plot_scr(r"C:\tmp\plot.lsp");
        assert!(
            s.contains("C:/tmp/plot.lsp"),
            "backslashes not replaced:\n{s}"
        );
    }

    #[test]
    fn scr_ends_with_quit_y() {
        let s = generate_plot_scr("/tmp/plot.lsp");
        let lines: Vec<&str> = s.lines().collect();
        let n = lines.len();
        assert!(n >= 2);
        assert_eq!(lines[n - 2].trim(), "QUIT");
        assert_eq!(lines[n - 1].trim(), "Y");
    }

    #[test]
    fn parse_plot_ok_returns_path() {
        let path = parse_plot_output("Loading...\nRESULT:OK:/tmp/out.pdf\n").unwrap();
        assert_eq!(path, "/tmp/out.pdf");
    }

    #[test]
    fn parse_plot_ok_trims_whitespace() {
        let path = parse_plot_output("  RESULT:OK:/tmp/out.pdf  ").unwrap();
        assert_eq!(path, "/tmp/out.pdf");
    }

    #[test]
    fn parse_plot_error_returns_err() {
        let e = parse_plot_output(
            "RESULT:ERROR:layout-not-found:Sheet99 available:[\"Model\",\"Layout1\"]",
        )
        .unwrap_err();
        assert!(e.to_string().contains("layout-not-found"), "got: {e}");
    }

    #[test]
    fn parse_plot_warn_returns_err() {
        let e = parse_plot_output("RESULT:WARN:pdf-not-found-after-plot").unwrap_err();
        assert!(e.to_string().contains("pdf-not-found"), "got: {e}");
    }

    #[test]
    fn parse_plot_missing_sentinel_is_err() {
        let e = parse_plot_output("Loaded drawing. Done.").unwrap_err();
        assert!(e.to_string().contains("RESULT"), "got: {e}");
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    fn plot_to_pdf_errors_on_non_windows() {
        let err = plot_to_pdf(
            std::path::Path::new("dummy.dwg"),
            "Layout1",
            std::path::Path::new("/tmp/out.pdf"),
        )
        .unwrap_err();
        assert!(err.to_string().contains("Windows"), "got: {err}");
    }

    #[test]
    fn plot_to_pdf_rejects_non_dwg_input_before_engine_launch() {
        let drawing = std::env::temp_dir().join("dummy.dxf");
        let output_pdf = std::env::temp_dir().join("out.pdf");

        let err = plot_to_pdf(&drawing, "Layout1", &output_pdf).unwrap_err();

        let msg = err.to_string();
        assert!(
            msg.contains("plot_to_pdf only supports DWG input"),
            "got: {err}"
        );
        assert!(!msg.contains("accoreconsole"), "got engine error: {err}");
    }

    #[test]
    fn plot_to_pdf_rejects_relative_output_before_engine_launch() {
        let drawing = std::env::temp_dir().join("dummy.dwg");

        let err = plot_to_pdf(&drawing, "Layout1", std::path::Path::new("out.pdf")).unwrap_err();

        let msg = err.to_string();
        assert!(
            msg.contains("output PDF path must be absolute"),
            "got: {err}"
        );
        assert!(!msg.contains("accoreconsole"), "got engine error: {err}");
    }
}
