use std::path::Path;

use anyhow::{anyhow, Result};

use crate::{
    activation::{MutationCapability, SelectedActivation},
    activation_platform::ProductionMutationRuntime,
    ops::profiles::{Profile, TitleBlockFingerprint},
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WriteReport {
    pub target_inserts: usize,
    pub attributes_written: usize,
}

fn escape_lisp_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Generate the AutoLISP source that writes `tag_values` onto every INSERT
/// matching the resolved title-block fingerprint, then QSAVEs. Output is a
/// complete self-contained `.lsp` file — no external dependencies.
pub fn generate_write_lsp(
    fingerprint: &TitleBlockFingerprint,
    tag_values: &[(String, String)],
) -> String {
    let upper_block = &fingerprint.block_name;
    let expected_tags = fingerprint
        .attribute_tags
        .iter()
        .map(|tag| format!("\"{}\"", escape_lisp_string(tag)))
        .collect::<Vec<_>>()
        .join(" ");
    let requested_tags = tag_values
        .iter()
        .map(|(tag, _)| format!("\"{}\"", escape_lisp_string(tag)))
        .collect::<Vec<_>>()
        .join(" ");
    let mut s = String::new();

    s.push_str(";; Generated by autocad-mcp — do not edit\n");

    // Helper: walk ATTRIB sub-entities and update the one matching TAG
    s.push_str("(defun _mcpw:set-attrib (ent tag value / utag e d n)\n");
    s.push_str("  (setq utag (strcase tag) e (entnext ent) n 0)\n");
    s.push_str("  (while (and e (setq d (entget e)) (= \"ATTRIB\" (cdr (assoc 0 d))))\n");
    s.push_str("    (if (= utag (strcase (cdr (assoc 2 d))))\n");
    s.push_str("      (progn (entmod (subst (cons 1 value) (assoc 1 d) d)) (setq n (1+ n))))\n");
    s.push_str("    (setq e (entnext e)))\n");
    s.push_str("  (if (> n 0) (entupd ent))\n");
    s.push_str("  n)\n\n");

    s.push_str("(defun _mcpw:attrib-count (ent tag / utag e d n)\n");
    s.push_str("  (setq utag (strcase tag) e (entnext ent) n 0)\n");
    s.push_str("  (while (and e (setq d (entget e)) (= \"ATTRIB\" (cdr (assoc 0 d))))\n");
    s.push_str("    (if (= utag (strcase (cdr (assoc 2 d)))) (setq n (1+ n)))\n");
    s.push_str("    (setq e (entnext e)))\n");
    s.push_str("  n)\n\n");

    s.push_str("(defun _mcpw:member-ci-p (x xs / ux found)\n");
    s.push_str("  (setq ux (strcase x) found nil)\n");
    s.push_str("  (while xs\n");
    s.push_str("    (if (= ux (strcase (car xs))) (setq found T))\n");
    s.push_str("    (setq xs (cdr xs)))\n");
    s.push_str("  found)\n\n");

    s.push_str("(defun _mcpw:insert-tags (ent / e d tags tag)\n");
    s.push_str("  (setq e (entnext ent) tags nil)\n");
    s.push_str("  (while (and e (setq d (entget e)) (= \"ATTRIB\" (cdr (assoc 0 d))))\n");
    s.push_str("    (setq tag (strcase (cdr (assoc 2 d))))\n");
    s.push_str("    (if (not (_mcpw:member-ci-p tag tags)) (setq tags (cons tag tags)))\n");
    s.push_str("    (setq e (entnext e)))\n");
    s.push_str("  tags)\n\n");

    s.push_str("(defun _mcpw:all-members-p (expected actual / ok xs)\n");
    s.push_str("  (setq ok T xs expected)\n");
    s.push_str("  (while xs\n");
    s.push_str("    (if (not (_mcpw:member-ci-p (car xs) actual)) (setq ok nil))\n");
    s.push_str("    (setq xs (cdr xs)))\n");
    s.push_str("  ok)\n\n");

    s.push_str("(defun _mcpw:tags-match-p (ent expected / actual)\n");
    s.push_str("  (setq actual (_mcpw:insert-tags ent))\n");
    s.push_str(
        "  (and (= (length actual) (length expected)) (_mcpw:all-members-p expected actual)))\n\n",
    );

    s.push_str("(defun _mcpw:requested-tags-valid-p (ent requested / ok xs)\n");
    s.push_str("  (setq ok T xs requested)\n");
    s.push_str("  (while xs\n");
    s.push_str("    (if (/= 1 (_mcpw:attrib-count ent (car xs))) (setq ok nil))\n");
    s.push_str("    (setq xs (cdr xs)))\n");
    s.push_str("  ok)\n\n");

    // Main function: first collect and validate every exact-fingerprint target.
    // Mutation starts only after all requested tags have exactly one occurrence
    // on every target.
    s.push_str(
        "(defun _mcpw:apply ( / ss i ent d blk expected-tags requested-tags targets valid \
         target-count attr-count)\n",
    );
    s.push_str(&format!(
        "  (setq ss (ssget \"X\" '((0 . \"INSERT\") (66 . 1))) expected-tags (list {expected_tags}) requested-tags (list {requested_tags}) targets nil valid T target-count 0 attr-count 0)\n"
    ));
    s.push_str("  (if ss\n");
    s.push_str("    (progn\n");
    s.push_str("      (setq i 0)\n");
    s.push_str("      (while (< i (sslength ss))\n");
    s.push_str("        (setq ent (ssname ss i) d (entget ent) blk (cdr (assoc 2 d)))\n");
    s.push_str(&format!(
        "        (if (and (= \"{}\" (strcase blk)) (_mcpw:tags-match-p ent expected-tags))\n",
        upper_block
    ));
    s.push_str("          (progn\n");
    s.push_str("            (setq target-count (1+ target-count))\n");
    s.push_str("            (setq targets (cons ent targets))\n");
    s.push_str(
        "            (if (not (_mcpw:requested-tags-valid-p ent requested-tags)) \
         (setq valid nil))\n",
    );
    s.push_str("            ))\n");
    s.push_str("        (setq i (1+ i)))))\n");
    s.push_str("  (if (and (> target-count 0) valid)\n");
    s.push_str("    (while targets\n");
    s.push_str("      (setq ent (car targets))\n");
    for (tag, value) in tag_values {
        s.push_str(&format!(
            "      (setq attr-count (+ attr-count (_mcpw:set-attrib ent \"{}\" \"{}\")))\n",
            escape_lisp_string(tag),
            escape_lisp_string(value),
        ));
    }
    s.push_str("      (setq targets (cdr targets))))\n");
    s.push_str("  (list valid target-count attr-count))\n\n");

    // Invoke, branch on result
    s.push_str("(setq _mcpw:result (_mcpw:apply))\n");
    s.push_str(
        "(setq _mcpw:valid (car _mcpw:result) _mcpw:targets (cadr _mcpw:result) \
         _mcpw:attrs (caddr _mcpw:result))\n",
    );
    s.push_str("(if (= _mcpw:targets 0)\n");
    s.push_str("  (princ \"\\nRESULT:WARN:no-title-block-found\\n\")\n");
    s.push_str("  (if (not _mcpw:valid)\n");
    s.push_str("    (princ \"\\nRESULT:WARN:ambiguous-requested-title-block-tag\\n\")\n");
    s.push_str(&format!(
        "    (if (/= _mcpw:attrs (* _mcpw:targets {}))\n",
        tag_values.len()
    ));
    s.push_str("      (princ (strcat \"\\nRESULT:WARN:partial-write:\" (itoa _mcpw:targets) \":\" (itoa _mcpw:attrs) \"\\n\"))\n");
    s.push_str(
        "      (progn (command \"_.QSAVE\") \
         (princ (strcat \"\\nRESULT:OK:\" (itoa _mcpw:targets) \":\" (itoa _mcpw:attrs) \"\\n\"))))))\n",
    );
    s.push_str("(princ)\n");

    s
}

/// Generate the AutoCAD command script (.scr) that sets up the headless
/// environment, loads the given .lsp file, and exits.
/// `lsp_path` is the absolute path on disk (Windows or Unix); backslashes
/// are converted to forward slashes, which AutoCAD accepts on all platforms.
pub fn generate_write_scr(lsp_path: &str) -> String {
    let lsp_forward = lsp_path.replace('\\', "/");
    format!(
        "(setvar \"SECURELOAD\" 0)\n\
         (setvar \"FILEDIA\" 0)(setvar \"CMDDIA\" 0)\n\
         (load \"{lsp_forward}\")\n\
         QUIT\n\
         Y\n"
    )
}

/// Parse accoreconsole stdout for the `RESULT:` sentinel written by the
/// generated script. Returns write counts on `RESULT:OK:TARGETS:ATTRIBUTES`,
/// `Err` otherwise.
#[cfg(any(target_os = "windows", test))]
pub(crate) fn parse_result_output(output: &str) -> Result<WriteReport> {
    for line in output.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("RESULT:") {
            if let Some(counts) = rest.strip_prefix("OK:") {
                let mut parts = counts.split(':');
                let targets = parts
                    .next()
                    .ok_or_else(|| anyhow!("missing target count in RESULT sentinel"))?
                    .parse::<usize>()?;
                let attrs = parts
                    .next()
                    .ok_or_else(|| anyhow!("missing attribute count in RESULT sentinel"))?
                    .parse::<usize>()?;
                if parts.next().is_some() {
                    return Err(anyhow!("too many fields in RESULT sentinel"));
                }
                return Ok(WriteReport {
                    target_inserts: targets,
                    attributes_written: attrs,
                });
            }
            if let Some(msg) = rest.strip_prefix("WARN:") {
                return Err(anyhow!("write warning: {msg}"));
            }
        }
    }
    Err(anyhow!(
        "no RESULT sentinel found in accoreconsole output; \
         the script may not have loaded or the drawing failed to open"
    ))
}

/// Write title-block attributes in a DWG file via accoreconsole.
///
/// On non-Windows platforms this always returns `Err` — accoreconsole
/// is a Windows-only binary.
#[cfg(test)]
pub fn write_dwg(
    drawing: &Path,
    profile: &Profile,
    tag_values: &[(String, String)],
) -> Result<WriteReport> {
    write_dwg_impl(drawing, profile, tag_values, None)
}

pub fn write_dwg_with_activation(
    drawing: &Path,
    profile: &Profile,
    tag_values: &[(String, String)],
    runtime: &ProductionMutationRuntime,
) -> Result<WriteReport> {
    let drawing_format = crate::reader::inspect_dwg_version(drawing).map_err(|error| {
        anyhow!("failed to inspect persisted DWG version before title-block activation: {error}")
    })?;
    let selected = runtime
        .acquire_for_format(MutationCapability::DwgTitleBlockMutation, &drawing_format)
        .map_err(|error| {
            anyhow!(
                "AutoCAD activation failed before DWG title-block mutation: {error}; drawing={}",
                drawing.display()
            )
        })?;
    write_dwg_impl(drawing, profile, tag_values, Some(&selected))
}

fn write_dwg_impl(
    drawing: &Path,
    profile: &Profile,
    tag_values: &[(String, String)],
    selected: Option<&SelectedActivation>,
) -> Result<WriteReport> {
    #[cfg(not(target_os = "windows"))]
    {
        let _ = (drawing, profile, tag_values, selected);
        Err(anyhow!(
            "accoreconsole is only available on Windows; \
             cannot write DWG on this platform"
        ))
    }

    #[cfg(target_os = "windows")]
    {
        use crate::engine;

        let staging = engine::create_staging_dir()?;
        let staging_path = staging.path();

        let fingerprint = profile.title_block_fingerprint();
        let lsp_content = generate_write_lsp(&fingerprint, tag_values);
        let lsp_path = staging_path.join("write-title-block.lsp");
        std::fs::write(&lsp_path, lsp_content)?;

        let lsp_path_str = lsp_path
            .to_str()
            .ok_or_else(|| anyhow!("staging path is not valid UTF-8"))?;
        let scr_content = generate_write_scr(lsp_path_str);
        let scr_path = staging_path.join("write-title-block.scr");
        std::fs::write(&scr_path, scr_content)?;

        let output = match selected {
            Some(selected) => engine::run_accoreconsole_with_selected_activation(
                selected,
                drawing,
                &scr_path,
                staging_path,
                &[],
            ),
            None => {
                let exe = engine::find_accoreconsole()?;
                engine::run_accoreconsole(&exe, drawing, &scr_path, staging_path)
            }
        }?;
        parse_result_output(&output)
        // `staging` drops here, cleaning up the temp dir
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ops::profiles::TitleBlockFingerprint;

    fn fingerprint(block: &str, tags: &[&str]) -> TitleBlockFingerprint {
        TitleBlockFingerprint::new(block, tags.iter().copied())
    }

    #[test]
    fn lsp_contains_block_name_uppercased() {
        let s = generate_write_lsp(
            &fingerprint("AUTOCAD_MCP_GENERIC", &["REVISION"]),
            &[("REVISION".into(), "P02".into())],
        );
        assert!(s.contains("AUTOCAD_MCP_GENERIC"), "got:\n{s}");
    }

    #[test]
    fn lsp_contains_tag_and_value() {
        let s = generate_write_lsp(
            &fingerprint("BLK", &["TAG1"]),
            &[("TAG1".into(), "VAL1".into())],
        );
        assert!(s.contains("TAG1"), "got:\n{s}");
        assert!(s.contains("VAL1"), "got:\n{s}");
    }

    #[test]
    fn lsp_multiple_fields_all_present() {
        let fields = vec![
            ("REVISION".into(), "P01".into()),
            ("DRAWING_NUMBER".into(), "ABC-001".into()),
        ];
        let s = generate_write_lsp(
            &fingerprint("BLK", &["REVISION", "DRAWING_NUMBER"]),
            &fields,
        );
        assert!(s.contains("REVISION"));
        assert!(s.contains("P01"));
        assert!(s.contains("DRAWING_NUMBER"));
        assert!(s.contains("ABC-001"));
    }

    #[test]
    fn lsp_escapes_double_quotes_in_value() {
        let fields = vec![("T".into(), r#"say "hi""#.into())];
        let s = generate_write_lsp(&fingerprint("BLK", &["T"]), &fields);
        assert!(s.contains(r#"say \"hi\""#), "got:\n{s}");
    }

    #[test]
    fn lsp_escapes_backslash_in_value() {
        let fields = vec![("T".into(), r"back\slash".into())];
        let s = generate_write_lsp(&fingerprint("BLK", &["T"]), &fields);
        assert!(s.contains(r"back\\slash"), "got:\n{s}");
    }

    #[test]
    fn lsp_contains_result_sentinels() {
        let s = generate_write_lsp(&fingerprint("BLK", &["T"]), &[("T".into(), "V".into())]);
        assert!(s.contains("RESULT:OK:"), "got:\n{s}");
        assert!(s.contains("RESULT:WARN:no-title-block-found"), "got:\n{s}");
        assert!(s.contains("_.QSAVE"), "got:\n{s}");
    }

    #[test]
    fn lsp_contains_fingerprint_tag_set_check() {
        let s = generate_write_lsp(
            &fingerprint("AUTOCAD_MCP_GENERIC", &["REVISION", "DRAWING_NUMBER"]),
            &[("REVISION".into(), "P02".into())],
        );
        assert!(s.contains("_mcpw:tags-match-p"), "got:\n{s}");
        assert!(s.contains("DRAWING_NUMBER"), "got:\n{s}");
        assert!(s.contains("REVISION"), "got:\n{s}");
    }

    #[test]
    fn lsp_preflights_requested_tag_multiplicity_before_mutation() {
        let s = generate_write_lsp(
            &fingerprint("BLK", &["REVISION", "SHEET"]),
            &[("REVISION".into(), "P02".into())],
        );
        assert!(s.contains("_mcpw:attrib-count"), "got:\n{s}");
        assert!(s.contains("_mcpw:requested-tags-valid-p"), "got:\n{s}");
        assert!(
            s.contains("(if (and (> target-count 0) valid)\n    (while targets"),
            "mutation must be guarded by the complete preflight:\n{s}"
        );
        assert!(
            s.contains("RESULT:WARN:ambiguous-requested-title-block-tag"),
            "got:\n{s}"
        );
    }

    #[test]
    fn scr_starts_with_secureload_zero() {
        let s = generate_write_scr("/tmp/x.lsp");
        let first_line = s.lines().next().unwrap();
        assert_eq!(first_line, r#"(setvar "SECURELOAD" 0)"#, "got:\n{s}");
    }

    #[test]
    fn scr_contains_load_call_with_forward_slashes() {
        let s = generate_write_scr(r"C:\tmp\x.lsp");
        assert!(s.contains("C:/tmp/x.lsp"), "backslashes not replaced:\n{s}");
    }

    #[test]
    fn scr_ends_with_quit_y() {
        let s = generate_write_scr("/tmp/x.lsp");
        let lines: Vec<&str> = s.lines().collect();
        let n = lines.len();
        assert!(n >= 2);
        assert_eq!(lines[n - 2].trim(), "QUIT");
        assert_eq!(lines[n - 1].trim(), "Y");
    }

    #[test]
    fn parse_result_ok_succeeds() {
        let report = parse_result_output("Loading...\nRESULT:OK:2:4\n").unwrap();
        assert_eq!(report.target_inserts, 2);
        assert_eq!(report.attributes_written, 4);
    }

    #[test]
    fn parse_result_ok_with_trailing_whitespace() {
        let report = parse_result_output("  RESULT:OK:1:2  ").unwrap();
        assert_eq!(report.target_inserts, 1);
        assert_eq!(report.attributes_written, 2);
    }

    #[test]
    fn parse_result_warn_becomes_err_with_reason() {
        let e = parse_result_output("RESULT:WARN:no-title-block-found").unwrap_err();
        assert!(e.to_string().contains("no-title-block-found"), "got: {e}");
    }

    #[test]
    fn parse_result_missing_sentinel_is_err() {
        let e = parse_result_output("Loading... done.").unwrap_err();
        assert!(e.to_string().contains("RESULT"), "got: {e}");
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    fn write_dwg_returns_err_on_non_windows() {
        use crate::ops::profiles::find_profile;
        let profile = find_profile("AUTOCAD_MCP_GENERIC").unwrap();
        let err = write_dwg(std::path::Path::new("dummy.dwg"), profile, &[]).unwrap_err();
        assert!(err.to_string().contains("Windows"), "got: {err}");
    }
}
